language: cpp

sudo: enabled

compiler:
  - gcc

matrix:
  include:
    - os: linux
      name: Ubuntu 16.04
      dist: xenial
      env:
      - BADGE=Ubuntu_16.04
      - MAKE=make
    - os: linux
      name: Ubuntu 18.04
      dist: bionic
      env:
      - BADGE=Ubuntu_18.04
      - MAKE=make
    - os: windows
      name: Windows
      env:
      - BADGE=Windows
      - MAKE=mingw32-make
    - os: osx
      name: OSX
      env:
      - BADGE=OSX
      - MAKE=make

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install ocl-icd-libopencl1 opencl-headers ocl-icd-opencl-dev liboctave-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
         sudo add-apt-repository -y ppa:intel-opencl/intel-opencl;
         sudo apt-get -q update;
         sudo apt-get -y install intel-opencl;
    fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install opencl-intel-cpu-runtime; fi

addons:
  apt:
    packages:
    - ocl-icd-libopencl1
    - opencl-headers
    - ocl-icd-opencl-dev
    - liboctave-dev
    update: true

script:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ${MAKE} -C src oct; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ${MAKE} -C src clean; fi
    - ${MAKE} -C src
    - bin/mcxcl -L
